phoenix-pilot/phoenix-pilot-core

- quadcontrol/pid.c
- quadcontrol/pid.h
- add missing gains in D and I
- add maximum value for integral part of PID
PP-22
> quadcontrol: fix PID calculations

- .clang-format
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/lint.yml
This PR adds basic linter, it works the same as the `phoenix-project` template project.
> ci: add linter

- ekf/ekflib.c
- ekf/kalman_implem.c
- ekf/kalman_update_baro.c
- ekf/measurement.c
- ekf/tests/devekf.c
- fixed typos in ekflib.c leading to only X position being saved
- removed ekf thread end log that sometimes crashes the thread
- ekf barometer measurement changes
- barometer speed not fused into state
- ekf returns barometer height as enuZ altitude
> ekf: ekflib returns fix + treat barometer height as altitude

- ekf/Makefile
- ekf/ekflib.c
- ekf/include/ekflib.h
- ekf/kalman_implem.c
- ekf/kalman_update_baro.c
- ekf/kalman_update_imu.c
- ekf/measurement.c
- ekf/sensc.c
- ekf/tests/devekf.c
- ekf/tests/sensortest.c
- quadcontrol/control.c
- quadcontrol/pid.c
- quadcontrol/pid.h
Multiple commits, all but the first ([devekf: add selection to print versors or attitude](https://github.com/phoenix-pilot/phoenix-pilot-core/commit/dd538f86337b874e910987409eff4a1bdf628bc2)) were clang-format-ed before pushing.
Changes regarding minimizing accelerometer measurement noise impact on attitude estimation. Main changes were:
- add acceleration logging possibilities to test applications
- use ekf filtered accelerations in attitude estimation instead of basing attitude estimation on raw accelerometer measurements
- heavily increased accelerometer noise factor in ekf R matrix
- change in quadcontrol pid calculations so that they do not use error rate derrivative, but angular rates from ekf
- small naming fixes
High levels of noise were found in signals on which attitude …
> AHRS: Improve accelerometer noise handling

- quadcontrol/control.c
- quadcontrol/mma.c
JIRA: PD-50
Moved quadrocopter initialization to child process. Fixes problem where after fork ekf_getState() was not reading the newest data.
> quadcontrol: revert to use `vfork()` and signal handling changes

- quadcontrol/control.c
- quadcontrol/control.h
- add target attitude parsing from `etc/quad.conf`
- add target attitude usage in pid calculations
> quad-control: add target attitude and enable yaw pid calculations

- ekf/ekflib.c
- ekf/include/ekflib.h
- quadcontrol/control.c
- quadcontrol/control.h
- quadcontrol/pid.c
- quadcontrol/pid.h
Currently no boundary values check is performed on values that go to pid. Proposed solution:
- adds boundary values specification in ekflib
- adds reading those ekflib bounds in quad-control:control.c
- accounts for boundary values in pid calculation process
Symmetric boundary values are assumed.
> quad-control: accounting for angles boundary values in pid calculations

- algebra/include/matrix.h
This PR adds `matrix_at()` function to the `matrix` library.
This function return a pointer to matrix element in specified row and column.
JIRA: PP-71
Help operating with matrices and testing.
> algebra: adding `matrix_at()` function to `matrix` library

- algebra/include/matrix.h
- algebra/matrix.c
JIRA: PP-71
Bugfix - the `matrix_t` structure elements are `unsigned int` but values passed to `matrix_bufAlloc()` are signed. This causes casting errors and overall mess.
> algebra/matrix: fix `matrix_bufAlloc()` arguments unsignedness

- algebra/tests/matrix/various.c
JIRA: PP-71
This PR is making `matrix_zeroes()` test more precise and more similar to standard used of this function
More precised tests
> algebra: fixing `matrix_zeroes()` test

- algebra/tests/matrix/basic_interactions.c
- algebra/tests/matrix/tools.c
- algebra/tests/matrix/tools.h
- algebra/tests/matrix/various.c
JIRA: PP-71
This PR is adding additional tests for `matrix_zeroes`
More precise testing
> algebra: additional tests for `matrix_zeroes()` function

- quadcontrol/Makefile
- quadcontrol/mma.c
Using `libmctl` rewrite procedures in quadcontrol:mma module.
This branch is rebased on:
- https://github.com/phoenix-pilot/phoenix-pilot-core/pull/72
- https://github.com/phoenix-pilot/phoenix-pilot-core/pull/38
- https://github.com/phoenix-pilot/phoenix-pilot-core/pull/39
- https://github.com/phoenix-pilot/phoenix-pilot-core/pull/72
> mma: use `libmctl` procedures to control engines

- algebra/tests/main.c
- algebra/tests/quat/various.c
JIRA: PP-71
This PR adds tests for `quat_add` function.
> algebra: adding tests for `quat_add` function

- algebra/include/matrix.h
JIRA: PP-89
Some inline functions in `libalgeb` header files were declared not `static`. `static` keyword was added.
> algebra: change all `inline` functions in `matrix.h` to `static inline`

- calib/Makefile
- calib/calib.h
- calib/hmap.c
- calib/hmap.h
- calib/mag.c
- calib/magiron.c
- calib/magmot.c
- calib/main.c
- used linked list for procedures registration
- calibration file read/write procedures undeclared
JIRA: PP-89
Drone calibration tool framework. Each calibration procedure registers itself via constructor using static structure from its source file.
Uses:
- https://github.com/phoenix-pilot/phoenix-pilot-core/pull/94
- https://github.com/phoenix-pilot/phoenix-pilot-core/pull/94
> calib: calibration tool framework

- calib/Makefile
- calib/calibtool.h
- calib/magiron.c
- calib/magmot.c
- calib/main.c
- libs/calib/calib.c
- libs/calib/calib.h
Recent addition of `libcalib` makes a lot of `calibttol` redundant and unnecessary. Changes in this PR make `calibtool` dependent on `libcalib`
> calibtool: switch to `libcalib` library

- ekf/measurement.c
- no more needed after libcalib implementation
JIRA: PP-89
After magnetometer calibration is done in libsensc there is no nedd for another in ekf.
> ekf: remove magnetometer calibration

- libs/calib/calib.c
- libs/sensc/corr.c
- changes in pwm file read as it requires rewinding on each read
- Missing assignment found in magmot correction resulting in not reading parameters.
- Magmot correction sign was flipped resulting in overcompensation
This brunch is
> calib: corrections after integration tests

- algebra/tests/matrix/addition_and_subtraction.c
JIRA: PP-71
Checking `A -= B` behavior of `matrix_sub` function
> algebra: adding tests for self subtraction in `matrix_sub` function

- algebra/include/quat.h
- algebra/quat.c
- algebra/tests/main.c
- algebra/tests/quat/various.c
This PR changes behavior of `quat_quat2euler` function. Now function does not change passed quaternion. Moreover it has tests for `quat_quat2euler` function.
Better interface for interaction with quaternions.
> Adding tests for `quat_quat2euler` function

- calib/magmot.c
- libs/calib/calib.h
- libs/sensc/corr.c
JIRA: PP-89
Magmot calibration is done only above throttle = 0.3. Calibration calclulated below may be artificial, as it should go to 0 when throttle approach 0. Quadratic fit may have minimum somewhere between 0 and cutoff, thus artificial correction may be applied:
Changed: 
- add cutoff macro
- use this macro to clip calibration if throttle is below the cutoff value
- extract motor impact calculation as inline function
> calib: handle magmot calibration below cutoff

- algebra/include/quat.h
- algebra/quat.c
- algebra/tests/main.c
- algebra/tests/quat/various.c
This PR adds new function `quat_axisAngle2quat` to `quat` libary. Function return quaternion which represents rotation along defined axis and about defined angle. Moreover I have added tests for this function.
Better interface for quaternions operations.
> Adding `quat_rotQuat` function

- algebra/include/quat.h
- algebra/quat.c
- algebra/tests/main.c
- algebra/tests/quat/various.c
In this PR I have fixed `quat_uvec2uvec` function. Now function check if passed vectors are parallel or antiparallel in a proper way. Moreover I have added tests for this function.
More robust functions.
> Fixing and adding tests for `quat_uvec2uvec` function

- algebra/matrix.c
JIRA: PP-71
Now function checks explicitly  if passed number of `rows` and `cols` are not equal to 0. This make this function less implementation dependent, because according to POSIX `calloc` can, but don't have to fail when gets zero elements to allocate.
Less implementation dependent function.
> algebra: fixing `matrix_bufAlloc` function

- algebra/include/quat.h
- algebra/quat.c
- algebra/tests/main.c
- algebra/tests/quat/various.c
- algebra/vec.c
In this PR fixes `quat_frameRot` function. No function is able to handle situation when second vector from frame of reference are parallel to each other. Moreover I have added tests to cover my changes.
Fixing potential problem
> Adding tests and fixing `quat_frameRot` function

- ekf/kalman_update_imu.c
> ekf: `qEst` sign fix

- libs/hmap/hmap.c
Function `hmap_insert` fails if there is already an entry with same key as we want to add.
Fixing incorrect behavior.
> `hmap` fix

- ekf/ekflib.c
- ekf/ekflib.h
- libs/rcbus/rcbus.c
- libs/rcbus/rcbus.h
- quadcontrol/control.c
ekf and rcbus thread have been located in parent's process map. It can caused an undefined behavior.
`fork` is used instead of `vfork`.
All threads all moved to the child process.
> quadcontrol: fix abort in control.c

- quadcontrol/config.c
- quadcontrol/config.h
- quadcontrol/control.c
- quadcontrol/mma.c
- quadcontrol/mma.h
- quadcontrol/pid.c
Two changes in this PR:
- partially dropping logging of quad-control as it is less usable now and takes time to print (lowers loop efficiency)
- implementing pid attenuation:
- pid values attenuation happens accordingly to attenuation factor
- pid values are straight multiplied by attenuation factor
- attenuation factor is calculated based on current throttle and attenuation factor curve specified by user
- attenuation factor curve has 3 points:
1) at throttle equal 0 and of `startVal` value
2) at throttle equal `startVal` and of `startVal` value
3) at throttle equal 1 and of `startVal` value
> quad-control: pid attenuation and log dropping

- quadcontrol/config.c
- quadcontrol/control.c
This PR fixes a problem with parsing files without the required header. As specified in `realloc` POSIX documentation when new size is equal to zero, function can return NULL. Previously this took place in `config_trimUnusedSpace`. As a result, this function returned an error and the caller function tried to free result data, which already was freed.
Additionally, all error messages now have a newline character at the end.
Report invalid file in a proper way.
> Fix problem with parsing file without required header

- algebra/Makefile
- algebra/include/matrix.h
- algebra/include/qdiff.h
- algebra/qdiff.c
JIRA: PP-90
Adding library `qdiff.h` that defines differentiation of:
- $\huge(\partial qvq)/(\partial q )$
- $\huge(\partial qvq)/(\partial v )$
- $\huge(\partial qv)/(\partial q )$
- $\huge(\partial qv)/(\partial v )$
$\huge q$ - quaternion
$\huge v$ - pure quaternion
- These equations are currently implemented _in situ_ in `libekf`. As they are somewhat generic it is better to store them in `libalgeb`.
- This change allows for writing tests to check the implementation of these and further optimalization 
These equations were inspired by this publication: [quaternion.pdf]( https://faculty.sites.iastate.edu/jia/files/inline-files/quaternion.pdf).
> algebra: add quaternion-vector differentiation library

- algebra/Makefile
- algebra/include/lma.h
- algebra/include/matrix.h
- algebra/lma.c
- algebra/matrix.c
- utils/Makefile
- utils/lmatest.c
-  adding `lma.h`: generic Levenberg–Marquardt algorithm (LMA) implementation in libalgeb 
- adding sample implementation of `lma.h` in _utils/_
LMA implementation follows mathematics described on wikipedia: https://en.wikipedia.org/wiki/Levenberg%E2%80%93Marquardt_algorithm
> algebra: Levenberg–Marquardt algorithm implementation

- algebra/include/matrix.h
- algebra/matrix.c
- calib/magiron.c
This calibration tool finds the calibration coefficients of soft iron and hardiron calibration.
JIRA: PP-89
Implementing proper **mag**netometer hard/soft **iron** (magiron) calibration procedure using Lavenberg-Marquardt least square fitting of ellipsoid transformation coefficients.
Proposed solution does not check for conic conditions during fitting, only checks if outcome parameters satisfies:
- soft iron calibration diagonal must contain non-negative values
- hard iron calibration vector must be within limits
Calibration procedure consist of:
- sampling the magnetometer with some spatial frequency (given with minimum angle of rotation between samples)
- fitting calibration parameters
- fitted parameters validity checks and save
The calibration formula is as follow
$$y = S(x - h)$$ …
> calibtool: add `magiron` calibration implementation

- libs/parser/parser.c
> parser.c: fix using uninitialized variable in parser_fieldGetFloat()

- libs/rcbus/rcbus.c
- libs/rcbus/rcbus.h
- quadcontrol/control.c
- utils/rclog.c
Loosing signal from radio receiver, loosing the receiver at all (disconnect) or system error on reading the receiver port now signal this in the form of error variable.
All current uses of `rcbus` got implemented with this error handling. 
Recent fly-away incident with drone shed a light on lack of failsafe feature in an event of receiver power-down.
Although the signal loss is not covered by this change, an event of receiver loosing supply voltage is covered as it will halt data transmission.
Loosing signal must be handled in the transmitter itself which may trigger some action on receiver if signal is lost as (for our fs-i6-x transmitter) is covered here:
- https://www.flysky-cn.com/journal/2021/2/21/about-the-flysky-remote-control-failsafe-function
> rcbus: radio loss coverage

- libs/rcbus/rcbus.c
- current state produces an error of undefined variable
JIRA: PP-138
Removing compilation warning of possible undefined variable state in `rcbus`.
> rcbus: initialize error in positive error state

- algebra/include/matrix.h
- algebra/matrix.c
This PR fixes bug with calculating sandwich operation, when the first matrix from arguments is transposed.
Bug fix
> algebra: fix `matrix_sandwitch` functions

- algebra/tests/matrix/add_sub.c
- algebra/tests/matrix/buffs.h
- algebra/tests/matrix/inverse.c
- algebra/tests/matrix/mulitiplication.c
- algebra/tests/matrix/sandwitch.c
- algebra/tests/matrix/various.c
- algebra/tests/tools.c
- algebra/tests/tools.h
This PR changes the behavior of `algebraTests_buffFiff`. Now this function fills whole matrix with single value when `BUFFILL_WRITE_ALL` is passed as an argument. In previous version this took plane when the length of passed table was equal to 1.
Moreover now this function return an information about potential errors.
Better looking interface
> Change behaviour of `algebraTests_buffFill`

- quadcontrol/control.c
- **manual abort procedure is simplified to SWD = HIGH and throttle down**
- radio receiver disconnect error is now time based as it was too verbose and polluted logs
- changed modes handling so that the least possible checks are done in radio handler, the rest is done in mode-specific routines
- routines for `quad_idle/disarm/arm` are just like typical flight modes routines and handle the RC signals and proceed forward or backwards.
Radio handler should only handle priority modes like abort and enforcing manual mode in case of drone misbehaving.
> quad-control: changes in modes handling

- algebra/tests/qdiff/tests.c
Changes test with wrong output matrix size. Now it uses statically allocated matrix same as `qpDiffV` tests.
More consistent testing methods.
> Change `qpDiffQ` tests: use statically allocated matrix in test

- algebra/lma.c
JIRA: PP-141
`lma_solveResidua` has wrong return type of float, should be int.
- https://github.com/phoenix-pilot/phoenix-pilot-core/issues/207
> lma: fix `lma_solveResidua` return type

- libs/parser/Makefile
Fixes how `libhmap` is added in makefile of `parser`. Old solution could lead to compilation fail.
Bug fix
> Fix adding `libhmap` in `parser` Makefile

- calib/accorth.c
- libs/calib/calib.c
- libs/calib/calib.h
- libs/sensc/corr.c
Addition of axis swapping/inversion solution in IMU initial rotation estimation. From now on measurements of IMU are not only rotated using quaternion but also their order is switched and inverted if necessary. 
Estimating IMU rotation only with quaternion has a room for an error if that rotation is big/complex (not along one axis). Instead of using only quaternion it may be easier to firstly switch axis order and/or invert some of them and then calculate the quaternion. 
This way big rotations are not included in the quaternion so it more correctly estimates the missalignment of the axis. This also makes the calibration procedure more robust i.e. differences between consecutive calibration procedures in calibtool are smaller
> calib: axis swapping in `accorth`

- ekf/Makefile
- ekf/logs/max_logs.c
- ekf/logs/max_logs.h
- ekf/logs/tests/Makefile
- ekf/logs/writer.c
This PR adds module, which estimates max possible logging volume.
In other to enable testing during compilation environmental variable `LOG_VOL_CHECK` must be set to `TRUE`.
Getting max possible log rate, which is not causing logs dropping or EKF slow down.
> Accessing max logging volume

- ekf/ekflib.c
- ekf/ekflib.h
- planecontrol/control.c
- quadcontrol/control.c
- utils/devekf.c
- utils/sensortest.c
Currently there are two flags that specify the data source for measurements: `EKF_INIT_SENC_SCR` and `EKF_INIT_LOG_SRC` and it is unclear what happens if both are up. This PR reduces flags to single one, which decides the source for EKF.
Clearer interface
> ekf: source selection flag unification

- ekf/logs/reader.c
Previously we tried to use `size_t` as signed type, which is incorrect. This PR fixes that with type change to `ssize_t`
Fixes incorrect variable usage.
> ekflog: fix issue with checking if `size_t` is less than zero

- utils/devekf.c
This PR fixes `devekf`, which was not closing after exiting with `q` key. It turns out that our `pthread_cancel` in `libphoenix` does not returns then it is called to cancel thread, which waits for join.
Robust and pleasant tools to work with.
> devekf hotfix

- calib/Makefile
- calib/accorth.c
- calib/gyrorth.c
- calib/linlsm.c
- calib/linlsm.h
- calib/magiron.c
- calib/magmot.c
- calib/main.c
- calib/tempimu.c
- ekf/meas.c
- ekf/meas.h
- libs/calib/calib.c
- libs/calib/calib.h
- libs/sensc/corr.c
- libs/sensc/corr.h
- libs/sensc/sensc.c
- libs/sensc/sensc.h
- quadcontrol/mma.c
- utils/devekf.c
- utils/senslog.c
- utils/sensortest.c
- adding imu temperature calibration `tempiumu`
- correction module more modular
- correction module initialization flags
Adding `tempimu` calibration type forced a change in `sensc` and `corr` so that it is possible to run only selected calibrations and corrections. It is because `tempimu` calibration must be applied on non-calirbated data and current `accorth` calibration must be done on `tempimu` calibrated data, yet it is no possible to do these calibrations together. 
This problem occurs also with `magiron`/`magmot` calibrations and `accorth`/`accrot` but there it was mitigated by joining calibration procedures. However to tidy it up these calibrations will need splitting and the correct order of calibration enforced in `calibtool` with `corrInitFlags`.
> pilot-core: imu temperature and gyrorth calibration + gps double usage

- ekf/kalman_update_imu.c
- ekf/meas.c
- ekf/meas.h
Previously during imu measurement normalization length of magnetic vector from calibration was calculated during every iteration. This PR fixes that.
Faster EKF iterations
> Fix calculating calibration vector length on every iteration
