phoenix-pilot/phoenix-pilot-core

quadcontrol/mma.c
quadcontrol/mma.h

Add basic implementation of MMA.
PP-24

mma: add motor mixing algorithm

---

Makefile
quadcontrol/mma.c

also:
- ESC base value equals PWM MIN scaler
PP-24

mma: use PWM declaration defined in a board config and initialize motors

---

quadcontrol/Makefile
quadcontrol/control.c
quadcontrol/control.h
quadcontrol/mma.c
quadcontrol/pid.c
quadcontrol/pid.h

quadcopter: add basic implementation of quadcopter control module

---

ekf/Makefile
ekf/ekflib.c
ekf/include/ekflib.h
ekf/kalman_core.c
ekf/kalman_core.h
ekf/kalman_implem.c
ekf/kalman_implem.h
ekf/kalman_update_baro.c
ekf/kalman_update_gps.c
ekf/kalman_update_imu.c
ekf/measurement.c
ekf/sensc.c
ekf/tests/devekf.c
ekf/tools/phmatrix.c
ekf/tools/phmatrix.h

ekf: correct calibration procedures + testing app introduction

---

ekf/ekflib.c
ekf/kalman_implem.c

JIRA: PD-43
Remove and fix compilation warnings

ekf: warning fixes

---

quadcontrol/control.c

quadcontrol: read PID configuration from /etc/quad.conf

---

quadcontrol/control.c

quadcontrol: handle return value from ekf

---

ekf/ekflib.c

ekflib: thread end handling

---

ekf/ekflib.c
ekf/kalman_implem.c
ekf/kalman_update_imu.c
ekf/measurement.c
ekf/tests/devekf.c
ekf/tools/rotas_dummy.c
ekf/tools/rotas_dummy.h

Two commits:
- ellipsoid compensation fixes:
- calculations of magnetic field done with milligauss (10^-7 T) unit
- updated magnetometer calibration parameters
- updated accelerometer calibration parameters
- _rotas_dummy_ vector and quaternion functions do not use large, by-value returns of `vec_t` or `quat_t` structures
- done together with ekf code refactor to fit changed functions
- updated descriptions of functions

ekf: ellipsoid compensation + rotas_dummy refactor

---

quadcontrol/pid.c
quadcontrol/pid.h

quadcontrol: add min intergal and change derivative calculation

---

quadcontrol/mma.c

quadcontrol/mma: change pwm calculation and add syslog

---

quadcontrol/control.c
quadcontrol/control.h
quadcontrol/mma.c
quadcontrol/pid.c

details:
- test duration is passed as argument,
- only roll and pitch is analysed
PP-24

quadcontrol: add code for testing quadcopter control

---

ekf/measurement.c

JIRA: PD-43
Ellipsoid calibration of accelerometer was getting wrong parameters by mistake.

ekf: ellipsoid calibration for accelerometer fixed

---

quadcontrol/control.c

quadcontrol: get max and min thrust values form quad.config

---

quadcontrol/control.c

more:
- add soft landing
PP-24

quadcontrol: remove code duplication

---

quadcontrol/control.c

quadcontrol: change naming convention thrust ->throttle

---

ekf/ekflib.c

JIRA: PP-60
Add synchronization on stateEngine data access between ekf thread and client thread calling ekf_stateGet()

ekflib: add synchronization in stateEngine access

---

quadcontrol/control.c
quadcontrol/mma.c
quadcontrol/mma.h

- provide arm and disarm mode in mma module
- apply new mma API to control module
- control module handles signals
PP-24

quadcontrol: handle signals and exit app in a correct way

---

quadcontrol/control.c
quadcontrol/mma.c

JIRA: PP-58
- moved target attitude set above `motorsControl()`
- mma motors order rewritten
- added `ANGLE_HOLD` option for `motorsControl` so that the set value is current value and we only react to sudden changes in it

quadcontrol: yaw control neccessary changes

---

algebra/tests/Makefile
algebra/tests/main.c
algebra/tests/matrix/various.c

This PR adds interface which enables writing tests for our algebra library. Moreover it adds one sample test - test of `matrix_zeroes` function.
This change is required to test fundamental numeric functions for our system.

Interface for algebra tests

---

algebra/tests/main.c
algebra/tests/matrix/README.md
algebra/tests/matrix/basic_interactions.c
algebra/tests/matrix/various.c

JIRA: PP-71
This PR is adding tests for function `matrix_at`

algebra: adding tests for `matrix_at()` function in `matrix` library

---

algebra/tests/main.c
algebra/tests/matrix/README.md
algebra/tests/matrix/basic_interactions.c

JIRA: PP-71
This PR is adding tests for function `matrix_buAlloc`

algebra: adding tests for `matrix_bufAlloc()` function

---

algebra/include/matrix.h

JIRA: PP-71
Including library `<stddef.h>  will resolve problem with function `matrix_at`
It resolves an issue: https://github.com/phoenix-pilot/phoenix-pilot-core/issues/44

algebra: including `<stddef.h>` library in `matrix.h`

---

algebra/matrix.c

JIRA: PP-71
Refactoring `matrix_bufFree` so it's implementation is more elegant.
More elegant (and slightly faster) implementation

algebra: refactoring `matrix_buFree()` function

---

algebra/tests/main.c
algebra/tests/matrix/README.md
algebra/tests/matrix/basic_interactions.c

JIRA: PP-71
This PR is adding tests for function `matrix_bufFree`
The more tests, the better

algebra: adding tests for `matrix_bufFree()` function

---

algebra/tests/main.c
algebra/tests/matrix/README.md
algebra/tests/matrix/various.c

JIRA: PP-71
This PR is adding test for function `matrix_trp`
We need to check if this function works properly.

algebra: adding test for `matrix_trp()` function

---

algebra/tests/matrix/basic_interactions.c

JIRA: PP-71
Now tests also checks function behavior when matrix is transposed

algebra: adding matrix_at() function tests for transposed matrices

---

algebra/include/matrix.h
algebra/tests/main.c
algebra/tests/matrix/README.md
algebra/tests/matrix/basic_interactions.c
algebra/tests/matrix/tools.c
algebra/tests/matrix/tools.h

This PR is adding new function to `matrix.h` library. It is adding `matrix_rowsGet` and matrix_colsGet` functions.
Giving potential user a very handy functions.

algebra: adding `matrix_rowsGet` and `matrix_colsGet` functions

---

algebra/tests/matrix/basic_interactions.c
algebra/tests/matrix/tools.c
algebra/tests/matrix/tools.h
algebra/tests/matrix/various.c

Renaming functions from `tools` library
Now naming is more consistent

Refactoring `tools` libary in `matrix` tests

---

algebra/tests/main.c
algebra/tests/matrix/tools.c
algebra/tests/matrix/tools.h
algebra/tests/matrix/various.c

JIRA: PP-71
This PR is adding test for function `matrix_diag`
We need to check if this function works properly.

algebra: adding tests for `matrix_diag()` function

---

libs/mctl/Makefile
libs/mctl/mctl.c
libs/mctl/mctl.h

JIRA: PP-89
Adding general motor control library `libmctl` with:
- engines init/deinit functions
- engines arming/disarming functions with safety control
- engines throttle control
More applications are goint to use engines, so good engines control module is needed. This PR share `tools/` structure with:
- https://github.com/phoenix-pilot/phoenix-pilot-core/pull/38

tools/mctl: add motor control library `libmctl`

---

algebra/tests/Makefile
algebra/tests/main.c
algebra/tests/quat/various.c

JIRA: PP-71
This PR adds tests for `quat_idenWrite` function
We want to be sure this this function work correctly.

algebra: adding tests for `quat_idenWrite`

---

algebra/tests/Makefile
algebra/tests/main.c
algebra/tests/vec/various.c

JIRA: PP-71
This PR is adding additional tests for `vec_sum`
More precise testing

algebra: adding tests for `vec_sum` function

---

libs/mctl/mctl.c
libs/mctl/mctl.h

- `mctl_init()` was refactored to meet race conditions that may appear in runtime
- `mctl_arm()` was aided with `armMode` enum to better distinguish the mode it is to be run.
- files were restructured to the correct order of functions according to libraries convention

libmctl: `mctl_init()` refactor and `mctl_arm()` modes addition

---

algebra/tests/main.c
algebra/tests/quat/various.c

JIRA: PP-71
This PR adds tests for `quat_piWrite` function.

algebra: adding tests for `quat_piWrite` function

---

algebra/tests/main.c
algebra/tests/vec/various.c

JIRA: PP-71
This PR adds tests for `vec_add` function.

algebra: adding tests for `vec_add` function

---

algebra/tests/main.c
algebra/tests/vec/various.c

JIRA: PP-71
This PR adds tests for `vec_diff` function.

algebra: adding tests for `vec_dif` function

---

algebra/tests/main.c

JIRA: PP-71
This PR reorders algebra tests, so it is more logical
To have better, easier to understand tests.

algebra: reordering algebra tests

---

algebra/tests/main.c
algebra/tests/vec/various.c

JIRA: PP-71
This PR adds tests for `vec_sub` function.

algebra: adding tests for `vec_sub` function

---

algebra/include/quat.h
algebra/quat.c

JIRA: PP-71
I have added these functions:
- `quat_cmp` - compares two quaternions
- `quat_sum` - safes sum of two quaternions to other quaternion (C = A + B)
- `quat_dif` - safes difference of two quaternions in other quaternion (C = A - B)
- `quat_sub` - subtracts two quaternions and safes the result in one of these (A -= B)
Better for flexing interface for this library.
https://github.com/phoenix-pilot/phoenix-pilot-core/issues/84
https://github.com/phoenix-pilot/phoenix-pilot-core/issues/83

algebra: adding some useful functions to quaternions library

---

algebra/include/matrix.h
algebra/matrix.c

JIRA: PP-71
Fixing behavior of some function from `matrix` library
We want to have safer functions
https://github.com/phoenix-pilot/phoenix-pilot-core/issues/68
https://github.com/phoenix-pilot/phoenix-pilot-core/issues/51
https://github.com/phoenix-pilot/phoenix-pilot-core/issues/50
https://github.com/phoenix-pilot/phoenix-pilot-core/issues/48
https://github.com/phoenix-pilot/phoenix-pilot-core/issues/47
https://github.com/phoenix-pilot/phoenix-pilot-core/issues/36

Fixing `matrix` library

---

algebra/include/vec.h
algebra/tests/main.c
algebra/tests/vec/various.c

In this PR we are adding new function `vec_cmp` to vectors library. Moreover I have added unit tests for this function.
Better interface to interact with vector library.

Adding `vec_cmp` function

---

algebra/tests/main.c
algebra/tests/vec/various.c

JIRA: PP-71
This PR contains tests for `vec_cross` functions
More precise testing.

algebra: adding tests for `vec_cross` function

---

algebra/tests/main.c
algebra/tests/quat/various.c

JIRA: PP-71
This PR contains tests for `quat_sum` function

algebra: addint tests for `quat_sum` functions

---

algebra/include/matrix.h
algebra/matrix.c
algebra/tests/main.c
algebra/tests/matrix/buffs.h
algebra/tests/matrix/tools.c
algebra/tests/matrix/tools.h
algebra/tests/matrix/tools_tests.c
algebra/tests/matrix/various.c

JIRA: PP-71
This PR adds new functionali to `matrix_writeSubmatrix`. Now function returns $-1$ when it is impossible to write submatrix. Additionally test for this function where made.
Safer functions
- [] Already covered by automatic testing.

P nieck/adding tests for `matrix_writeSubmatrix`

---

algebra/tests/main.c
algebra/tests/quat/various.c

This PR contains tests for `quat_dif` and `qaut_sub` functions. 

Adding tests for quat subtraction functions

---

algebra/tests/matrix/matrix_multiplication.c
algebra/tests/matrix/tools.h

JIRA: PP-71
No tests checks cases with incorrect matrix sizes.
More precise testing.

algebra: adding additional tests for `matrix_prod` function

---

algebra/tests/main.c
algebra/tests/quat/various.c

JIRA: PP-71
This PR contains tests for `quat_mlt` function.

algebra: adding tests for `quat_mlt` function

---

algebra/tests/main.c
algebra/tests/matrix/tools.h
algebra/tests/matrix/various.c

JIRA: PP-71
This PR contains tests for `matrix_cmp` function

algebra: adding tests for `matrix_cmp` function

---

algebra/tests/main.c
algebra/tests/quat/various.c

JIRA: PP-71
This PR contains tests for  `quat_times` function

algebra: adding tests for `quat_times` function

---

algebra/tests/vec/various.c

This PR adds special macro for testing vectors.
Solving problem with copying code in tests for `vec` library

Adding `TEST_ASSERT_EQUAL_VEC` macro

---

algebra/tests/quat/various.c

This PR adds special macro for testing quaternions.
Solving problem with copying code in tests for `quat` library.

Adding `TEST_ASSERT_EQUAL_QUAT` macro

---

algebra/tests/matrix/matrix_multiplication.c
algebra/tests/matrix/tools.h
algebra/tests/matrix/tools_tests.c
algebra/tests/matrix/various.c

This PR adds special macro for testing matrices.
Solving problem with copying code in tests for `matrix` libary

Adding `TEST_ASSERT_EQUAL_MATRIX` macro to matrix tests

---

algebra/tests/main.c
algebra/tests/quat/various.c

JIRA: PP-71
This PR contains tests fr `vec_cjg` function.

algebra: adding tests for `quat_cjg` function

---

algebra/tests/main.c
algebra/tests/vec/various.c

JIRA: PP-71
This PR contains tests for `matrix_times` function.

algebra: adding tests for `vec_times` functions

---

libs/calib/Makefile
libs/calib/calib.c
libs/calib/calib.h

This library will have common parts between calibration and correction utilities and will be used primarily by `calibtool` and `libsensc`

libcalib: implementation of common calibration library

---

algebra/tests/main.c
algebra/tests/vec/various.c

JIRA: PP-71
This PR contains tests for `vec_dot` function
More precise testing

algebra: adding tests for `vec_dot` function

---

calib/magmot.c
ekf/Makefile
ekf/ekflib.c
ekf/tests/sensortest.c
libs/calib/calib.c
libs/calib/calib.h
libs/sensc/Makefile
libs/sensc/corr.c
libs/sensc/corr.h
libs/sensc/sensc.c
libs/sensc/sensc.h
quadcontrol/Makefile

From now on libsensc has an option enabling corrections in runtime for measurements. `LIbcalib` features are used.

libsensc: using libcalib library to correct measurements

---

algebra/tests/main.c
algebra/tests/matrix/addition_and_subtraction.c
algebra/tests/matrix/tools.h

JIRA: PP-71
This PR contains tests for `matrix_sub` function.

algebra: adding tests for `matrix_sub` function

---

algebra/quat.c
algebra/tests/main.c
algebra/tests/quat/various.c

This PR contains test for `quat_sandwich` function. Moreover it fixes this function.

Tests for `quat_sandwich`

---

algebra/tests/matrix/addition_and_subtraction.c

JIRA: PP-71
This PR contains tests for `matrix_add` function concentrated on `A += B` functionality.

algebra: adding tests for self adding in `matrix_add` function

---

algebra/tests/main.c
algebra/tests/quat/various.c

JIRA: PP-71
This PR contains tests for `quat_normalize` function from vectors library
More precise testing.

algebra: adding tests for `quat_normalize` function

---

algebra/tests/main.c
algebra/tests/vec/various.c

JIRA: PP-71
This PR contains tests for `vec_normalize` function from vectors library

algebra: adding tests for `vec_normalize` function

---

algebra/matrix.c
algebra/tests/main.c
algebra/tests/matrix/sandwitch.c

This PR fixes `matrix_sparseSandwitch` function and adds tests for this function.
Better interface in `matrix` library and more precise tests.

Adding tests and fixing `matrix_sparseSandwitch` function

---

algebra/tests/main.c
algebra/tests/vec/various.c
algebra/vec.c

In this PR behavior of function `vec_normal` was changed. Now function returns perpendicular vector, when paraller vectors are passed to it. Moreover there are tests for this function.
Better interface for vectors library.
https://github.com/phoenix-pilot/phoenix-pilot-core/issues/117

Fixing `vec_normal` function

---

algebra/tests/main.c
algebra/tests/quat/various.c

JIRA: PP-71
This PR contains tests for `quat_vecRot` function.

algebra: adding tests for `quat_vecRot` function

---

calib/Makefile
calib/calibtool.h
calib/main.c
calib/motesc.c
libs/mctl/mctl.c
libs/mctl/mctl.h
libs/sensc/corr.c

Adding calibration procedure for ESC. 
This procedure is implemented in `mctl`, as it already has all pwm control structures and is called by `calibtool` utility.
Also removed one compilation warning introduced in correction module.
**This branch is going to be squashed in 4 commits after successful review:**
1) changes in calib module (first two commits)
2) changes in `mctl`
3) changes in `calibtool`
3) warning removal
This is how calibration cli works:

calibtool/mctl: add esc calibration procedure

---

quadcontrol/control.c
scripts/quadLive.py

Added logging of height to `quad-control` and do plotting utility `quadLive.py`
`quadLive.py` now looks like that:

pilot-core: height plotting/logging

---

ekf/kalman_implem.c

- found out that accelerometer reading may be trusted more
- resulting in more level/smooth flight

ekf: more trust in accelerometer readings

---

algebra/tests/matrix/sandwitch.c

This PR is fixing memory leaks form algebra tests.
Getting rid of a memory leak.

No memory leaks in algebra tests

---

ekf/Makefile
ekf/tests/altlog.c

JIRA: PP-69
`altlog` is ekf/sensorhub utility that allows to test ekf altitude estimation possibilities. It is possible to specify total sampling time and sampling interval to suite test needs. It instantiates `ekf` thread and communicates with sensorhub for direct pressure data.

ekf: add `altlog` testing utility

---

calib/Makefile
calib/motlin.c
libs/calib/calib.c
libs/calib/calib.h

This procedure compensates for drone engines scaling inequalities. Coefficients are obtained through manual quad-control operation. Drone must by run with different base throttles that do not allow for the drone to takeoff. When the drone levels itself the PWMs must be saved for each engine. From such dataset a line must be fitted to each engine points (where x is base throttle and y[] are PWMs that make the drone leveled). Coefficients of such lines are this calibration parameters.

calib: motor linear compensation

---

algebra/tests/quat/various.c

JIRA: PP-71
This PR contain additional test, which check the behavior fo `quat_cjg` when zero quaternion is passed.

algebra: adding additional test for `quat_cjg` function

---

algebra/tests/vec/various.c
algebra/vec.c

This PR fixes `vec_normalize` function. Now it return zero vector when zero vector is passed to it. Moreover I have added tests to cover my changes.
Better interface without bugs.

Fixing `vec_normalize` function

---

ekf/kalman_update_baro.c
libs/calib/Makefile
quadcontrol/control.c

- added missing dependency for libcalib
- warnings removal

pilot-core: dependency fix + warnings removal

---

libs/rcbus/Makefile
libs/rcbus/rcbus.c
libs/rcbus/rcbus.h

libs/bus: add library to read I-Bus packets

---

quadcontrol/Makefile
quadcontrol/control.c
quadcontrol/control.h

Handle RC messages in quad control unit. 
PP-75

quadcontrol: add manual UAV control via RC bus

---

calib/Makefile
libs/hmap/Makefile
libs/hmap/hmap.h

JIRA: PP-74
This PR adds `ifndefs` to `hmap.h` file and changes name of this library from `hmap` to `libhamp`
1. Fixing potential bug
2. Being more consistent with naming conventions

Fix `hmap`libary

---

Makefile
algebra/tests/Makefile
algebra/tests/matrix/basics.c
algebra/tests/tools.c
algebra/tests/tools.h

JIRA: PP-99
When we are building `host-generic-pilot` project then algebra tests will compile onto host pc.
https://github.com/phoenix-pilot/phoenix-pilot-project/pull/28

algebra tests: making tests run on host

---

.codespell_ignore
algebra/include/quat.h
algebra/quat.c
calib/Makefile
calib/accrot.c
calib/main.c
ekf/kalman_implem.h
ekf/kalman_update_imu.c
ekf/measurement.c
libs/calib/calib.c
libs/calib/calib.h
libs/sensc/corr.c
libs/sensc/corr.h
libs/sensc/sensc.c

This PR implements following things:
1) accelerometer rotation (`accrot`) calibration as a calibration type in `libcalib`
2) `accrot` calibration procedure in `calibtool` that can calculate calibration parameters
3) `accrot` parameters usage in `libsensc`
4) strict usage of NED frame of reference in calcuations across `ekf` and all calibration procedures 
And additionally:
- implements `quat_len()` function to algebra library

pilot-core: accelerometer calibration implementation

---

quadcontrol/control.c
quadcontrol/control.h

quadcontrol: modify flight state machine

---

algebra/tests/main.c
algebra/tests/quat/basics.c

This PR add tests for `quat_len` function

Add tests for quat len

---

planecontrol/Makefile
planecontrol/control.c
planecontrol/mma.c
planecontrol/mma.h

Basic implementation of this unit tests control of servos and main motor.
PP-106

planecontrol: add basic plane control unit

---

ekf/ekflib.c
ekf/kalman_update_imu.c
ekf/measurement.c
libs/mctl/mctl.c
quadcontrol/control.c
quadcontrol/mma.c
scripts/quadLive.py

Following changes were made to achieve working quadrocopter in real scenario flight

pilot-core: changes for flying practice

---

quadcontrol/Makefile
quadcontrol/config.c
quadcontrol/config.h
quadcontrol/control.c

This PR enables to parse flight scenario from file.
We don't have to recompile program in order to change flight scenario.
https://github.com/phoenix-pilot/phoenix-pilot-project/pull/36

Add flight scenario parser

---

ekf/ekflib.c
ekf/ekflib.h
ekf/kalman_core.c
ekf/kalman_core.h
ekf/kalman_implem.c
ekf/kalman_implem.h
ekf/kalman_update_baro.c
ekf/kalman_update_gps.c
ekf/kalman_update_imu.c
utils/devekf.c

- Sensor fusion between accelerometer and barometer
- no more separate variables for barometric height and barometric velocity
- direct fusion of baro data into position and velocity in state vector
- removal of dead code
- slight name change of barometric update stap macros/variables
- addition of height and vertical speed to devekf utility

ekf: changes for better height estimation

---

quadcontrol/control.c
scripts/quadLive.py

- After drone crash more verbose mode switching was added
- abort frame counter added, so now it needs at least `ABORT_FRAMES_THRESH` frames to switch to manual abort mode

quad-control: changes to logging logic

---

ekf/kalman_update_imu.c

JIRA: PP-107
Switching to use constant quaternion error instead of dynamic one.

ekf: remove dynamic quaternion error calculation

---

quadcontrol/config.c
quadcontrol/config.h
quadcontrol/control.c
quadcontrol/control.h

This PR uses `parser` library to get PIDs and other configuration information from file.
No code repetition. Two different modules don't do the same thing.
https://github.com/phoenix-pilot/phoenix-pilot-core/pull/175

Config parser

---

ekf/ekflib.c
libs/rcbus/rcbus.c
utils/sensortest.c

JIRA: PP-95
Adding `tid` argument to `threadJoin` function after updateing pilot-project

pilot-core: missing argument in `threadJoin`

---

ekf/Makefile
ekf/ekflib.c
ekf/ekflib.h
ekf/filters.c
ekf/filters.h
ekf/kalman_implem.c
ekf/kalman_implem.h
ekf/kalman_update_imu.c
ekf/log.c
ekf/log.h
ekf/meas.c
scripts/quadLive.py

Enhancing dead reckoning of height with following changes:
- implementing auxiliary, low pass filter on accelerometer data
- implementing z axis accelerometer bias estimation
For changes mentioned above the log module was implemented to get  data from various stages of ekf filtering.
Changes in PIDs brought by this PR are in:
- https://github.com/phoenix-pilot/phoenix-pilot-project/pull/39

ekf: accel filters and bias estimation

---

ekf/ekflib.c
ekf/ekflib.h
libs/rcbus/rcbus.c
libs/rcbus/rcbus.h

ekf & rcbus: apply new threadJoin interface

---

ekf/ekflib.c
ekf/kalman_update_imu.c
quadcontrol/config.c
quadcontrol/control.c
quadcontrol/control.h

Preliminary automatic modes introduction:
- more modularized control module for easy RC override possibility
- working implementation of `takeoff`, `hover` and `landing` procedure
- changes of z accel bias estimation

pilot-core: automatic modes introduction

---

ekf/meas.c

JIRA: PP-119
Utilization of new sensorhub feature of self-integration of gyro values. 
Currently time resolution of gyroscope data is as small as sensorhub polling frequency. Sensorhub now provides continuous integration of sensor data with sufficiently large span that it is good to utilize it. In case of ekf latency greater than 1ms we do not loose the data of angular speed.
Implementing features introduced in:
- https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/334

ekf: use gyro delta angle instead of direct gyro measurement

---

libs/sensc/sensc.c
utils/senslog.c

- fixing `sensc` gps file descriptor bug
- adding `senslog` gps logging capability (only latitude/longitude/satelites/fix are printed) 
This PR adds testing capability of GPS device output
- https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/342

sensc: fixing and checking gps data

---

calib/Makefile
libs/mctl/Makefile
libs/mctl/mctl.c
libs/mctl/mctl.h
planecontrol/Makefile
quadcontrol/Makefile
quadcontrol/mma.c

Implementing usage of new pwm api that enables batch write to the driver (multiple pwm channels with one message)
Implementing features introduced in:
- https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/337

libmctl: add batch writing function

---

ekf/Makefile
ekf/ekflib.c
ekf/filters.c
ekf/filters.h
ekf/kalman_core.c
ekf/kalman_core.h
ekf/kalman_implem.c
ekf/kalman_implem.h
ekf/kalman_update_baro.c
ekf/kalman_update_imu.c
ekf/meas.c
ekf/meas.h
quadcontrol/config.c
quadcontrol/config.h
quadcontrol/control.c
quadcontrol/mma.c
quadcontrol/mma.h
quadcontrol/pid.c
utils/devekf.c

- added control vector
- using measurements of gyroscope in prediction step for integration purposes without unnecessarily storing them in the state vector  
- addition of velocity and position estimation
- accelrometer measurements usage in ekf prediction step in integration equations
- introduces low pass filter on gyro data
- `devekf` silent mode (quietly run ekf without any logging) enable better development of ekf
- low pass filter on gyroscope input (only pitch and yaw signals)
- abandon filtering if:
- gyroscope signal is above 0.05 radians per second
- estimated gyroscope bias is above 0.01 radians per second

ekf: new mathematical model

---

ekf/Makefile
ekf/ekflib.c
ekf/kalman_implem.c
ekf/kalman_implem.h
libs/parser/parser.c
libs/parser/parser.h
planecontrol/Makefile
utils/Makefile

This PR changes how the configuration files are read. Now parser library is used.
1. Removing old temporary solution.
2. Making config reads more consistent
https://github.com/phoenix-pilot/phoenix-pilot-project/pull/42

Ekf config parser update

---

libs/parser/parser.c
libs/parser/parser.h
quadcontrol/config.c

This PR updates config parsing so it's using newly added functions.
Less redundancy in code

Update config parsing in quadcontrol

---

algebra/tests/quat/basics.c
algebra/tests/quat/rotations.c

Fixing file headers in quaternions tests.
Fixing misleading comment.

algebra tests: fix file titles

---

algebra/include/qdiff.h
algebra/qdiff.c
algebra/tests/Makefile
algebra/tests/README.md
algebra/tests/main.c
algebra/tests/qdiff/buffs.h
algebra/tests/qdiff/tests.c

Adding unit tests of one of the functions from quaternion derivatives library.
More robust interface for algebra library.

Add tests of `qvdiff_qpDiffQ` function

---

algebra/include/qdiff.h
algebra/qdiff.c
algebra/tests/main.c
algebra/tests/qdiff/buffs.h
algebra/tests/qdiff/tests.c

Adding unit tests of one of the functions from quaternion derivatives library.
More robust interface for algebra library.

Add tests for `qvdiff_qpDiffP` function

---

algebra/tests/qdiff/tests.c

PR fixes incorrect size of a testing matrix.
Correct tests, which helps finding bugs in code.

algebra test: fix `qvdiff_qpDiffP` tests

---

ekf/filters.c
ekf/kalman_update_imu.c
quadcontrol/control.c

pilot-core: preliminary position hold implementation

---

algebra/include/qdiff.h
algebra/qdiff.c
algebra/tests/main.c
algebra/tests/qdiff/buffs.h
algebra/tests/qdiff/tests.c

This PR provides unit tests for `qvdiff_qvqDiffV` function.
More precise testing

Add tests for `qvdiff_qvqDiffV` function

---

algebra/tests/qdiff/tests.c

Matrices used in two tests were transposed, when they should not be.
Better tests

qdiff tests: fix matrix transformation

---

algebra/qdiff.c
algebra/tests/main.c
algebra/tests/qdiff/buffs.h
algebra/tests/qdiff/tests.c

This PR provides unit tests for `qvdiff_qvqDiffQ` function. As well as necessary fixes for it.
More precise testing and robust algebra library.

Add tests for `qvdiff_qvqDiffQ` function

---

algebra/Makefile
algebra/include/statistics.h
algebra/statistics.c

JIRA: PP-143
Adding iterative variance and limits calculation functions as a separate module in `algebra` mofule.

algebra: add iterative statistics functions

---

ekf/ekflib.c

PR fixes deallocation of ekf.
Better cleaning up after execution.

ekf: fix deallocation

---

calib/magiron.c
ekf/ekflib.c
ekf/filters.c
ekf/kalman_implem.h
ekf/kalman_update_gps.c
ekf/kalman_update_imu.c
ekf/log.h
ekf/meas.c
ekf/meas.h
quadcontrol/control.c
utils/senslog.c

ekf: poshold minor changes

---

libs/sensc/Makefile
libs/sensc/vsensc.c

This PR enables running `devekf` utility on emulator, especially on `armv7a9-zynq7000-vpilot` project
Easier testing
https://github.com/phoenix-pilot/phoenix-pilot-project/pull/50

Enable running `devekf` on emulators

---

ekf/ekflib.c
ekf/kalman_implem.c
ekf/kalman_update_imu.c
ekf/meas.c
ekf/meas.h

ekf: single poll data

---

ekf/ekflib.c
ekf/kalman_implem.c

Fixes of small errors in ekf algebra:
- naming fixes
- using proper differentiation functions
- removing local differentiation implementations

ekf: algebra fixes

---

README.md
ekf/README.md

Updates README files and fixes some typos.
Better documentation

Update informations in README files and fix typos

---

Makefile
ekf/ekflib.c
ekf/kalman_implem.c
ekf/kalman_implem.h
ekf/log.c
ekf/log.h
ekf/tests/log/Makefile
ekf/tests/log/main.c
ekf/tests/log/tests.c

This PR changes how pilot collects logs.
- Different logic of specifying what to log. Now what to log is specified by names not number. Moreover user can specify precisely what to log by writing down all logging targets separated with commas.
- Logic of collecting logs is not asynchronous
Faster and more flexible way of collecting logs
https://github.com/phoenix-pilot/phoenix-pilot-project/pull/53

Change logging logic

---

ekf/ekflib.c
ekf/kalman_implem.c
ekf/log.h
ekf/meas.c

PR allows to log all data from sensors.
Able mocking sensor data

ekf meas: log all needed sensor data

---

scripts/rx/rxfile.py

PR removes some statistical problems with `rxfile` script. Unused imports and variables.
More readable code.

Rxfile hotfix

---

scripts/file_transfer/transfer.py

PR modifies transferring data from drone to host.
- script uses compressing
- allows to specify port for console and data transfer
- faster transfer
- more flexible API

Modify file transfer

---

ekf/log.c

Hot fix, which unnecessary `extern` keywords.
Making code consistent with coding conventions.

ekf logs: remove unnecessary `extern` kewords

---

ekf/ekflib.c
ekf/meas.c

PR moves time logging from main EKF loop to `meas` module
More consistent code

ekf: move time logging from main loop to `meas`

---

ekf/logs/reader.c
ekf/logs/reader.h
ekf/logs/tests/tests.c
ekf/logs/writer.c
ekf/logs/writer.h
ekf/meas.c

This PR removed prefix `sensc` from EKF logging module.
Shorter and clearer functions names.

Rename ekf log functions

---

ekf/filters.c

PR fixes a bug with not closing a file in filters.
closes #258
Deallocating not used resources.

filters: fix closing a file

---

ekf/Makefile
ekf/ekflib.c
ekf/ekflib.h
ekf/kalman_implem.c
ekf/kalman_implem.h
ekf/logs/reader.c
ekf/logs/reader.h
ekf/meas.c
ekf/meas.h
planecontrol/control.c
quadcontrol/control.c
utils/devekf.c
utils/sensortest.c

This PR adds possibility to use logs as an input data for meas module.
Ability to test EKF.
#TODO: test change

Meas source selection

---

ekf/ekflib.c
ekf/filters.c

In EKF filter module
- fixed memory leak
- fix ignoring filter module error
Program robustness.

ekf: fix filter module

---

ekf/ekflib.c
ekf/ekflib.h
ekf/logs/reader.c
ekf/logs/reader.h
ekf/logs/tests/tests.c
ekf/meas.c
ekf/meas.h
utils/devekf.c

Add ekf error reporting
Possibility not to ignore possible EKF errors.

Add error flags

---

Makefile
ekf/tests/example_expected_result
ekf/tests/test_runner/Makefile
ekf/tests/test_runner/config_file_handler.c
ekf/tests/test_runner/config_file_handler.h
ekf/tests/test_runner/main.c
ekf/tests/test_runner/result_check.c
ekf/tests/test_runner/result_check.h
utils/devekf.c

PR adds ekf test runner. It allows to run EKF using prepared logs and compare final ekf status with expected one.
Enable easy EKF functional tests.

Ekf test runner

---

ekf/ekflib.c
libs/mctl/Makefile

Changes necessary after building script for phoenix-rtos-project was updated in recent month.

pilot-core: changes after main repo update

---

libs/parser/doc/file.md
libs/parser/parser.c
scripts/ekf_logs/README.md
scripts/ekf_logs/common/formats/binary/bin_export.py
scripts/ekf_logs/common/formats/binary/bin_parser.py
scripts/ekf_logs/common/formats/csv/csv_export.py
scripts/ekf_logs/common/formats/csv/csv_parser.py
scripts/ekf_logs/common/formats/format.py
scripts/ekf_logs/common/models/__init__.py
scripts/ekf_logs/common/models/log_data.py
scripts/ekf_logs/common/models/log_reading.py
scripts/ekf_logs/common/models/utils.py
scripts/ekf_logs/common/models/visitor.py
scripts/ekf_logs/ekf_tests/const_data_test.py
scripts/ekf_logs/ekf_tests/test_scenario_creator.py
scripts/ekf_logs/generate_test_data.py
scripts/ekf_logs/logs_evaluations/context.py
scripts/ekf_logs/logs_evaluations/evaluations/missing_logs.py

Adds script to generate ekf test scenario with constant data
EKF functional tests
https://github.com/phoenix-pilot/phoenix-pilot-core/pull/270

Simple ekf test

---

libs/parser/parser.c

This PR fixes regex in parser library. Previous version had redundancy in their definition.
Regex, which works better and it's easier to read

Parser: fix regex build in redundant way

---

quadcontrol/config.c
quadcontrol/control.c
quadcontrol/mma.c
quadcontrol/pid.c
quadcontrol/pid.h

Changing simple PID controller to RPID controller which uses rate coefficient to calculate rate of convergence and then controls the output to get to target rate.
Better drone control.

quad-control: RPID controller

---

scripts/ekf_logs/README.md
scripts/ekf_logs/common/models/log_data.py
scripts/ekf_logs/common/models/utils.py
scripts/ekf_logs/logs_evaluations/context.py
scripts/ekf_logs/logs_evaluations/evaluations/__init__.py
scripts/ekf_logs/logs_evaluations/evaluations/gps_ekf_comparison.py
scripts/ekf_logs/logs_evaluations/factory.py
scripts/ekf_logs/requirements.txt

Adds ekf log evaluation to for GPS and EKF status position comparison.
Easier EKF verification

GPS EKF comparison script

---

scripts/ekf_logs/common/formats/binary/bin_export.py
scripts/ekf_logs/common/formats/binary/bin_parser.py
scripts/ekf_logs/common/formats/csv/csv_export.py
scripts/ekf_logs/common/formats/csv/csv_parser.py

PR fixes wrong parsing EKF attitude quaternion. Module assumed different quternion format from used library.
Correct plots for data analysis.

ekf log script: fix rotation parsing and exporting

---

algebra/include/qdiff.h
algebra/qdiff.c
ekf/kalman_implem.c
ekf/kalman_implem.h
ekf/kalman_update_gps.c
ekf/kalman_update_imu.c
quadcontrol/config.c
quadcontrol/config.h
quadcontrol/control.c
quadcontrol/control.h
quadcontrol/pid.c
quadcontrol/pid.h

Adding earth magnetic field declination to ekf as apriori parameter.

ekf: hovering improvements

---

scripts/ekf_logs/logs_evaluations/context.py
scripts/ekf_logs/logs_evaluations/evaluations/gps_ekf_comparison/geo_distance.py
scripts/ekf_logs/logs_evaluations/evaluations/gps_ekf_comparison/position_comparison.py

Add timestamps annotations in EKF-GPS logs comparison. For clarity timestamps are provided only for state just after GPS reading.
Easier log analysis.

State position timestamps in EKF-GPS logs comparion

---

ekf/kalman_implem.h

Add more precise information, about velocity in ekf status
Code, which is easier to understand

Add more precise information, about velocity in ekf status

---

scripts/ekf_logs/README.md
scripts/ekf_logs/logs_evaluations/evaluations/gps_ekf_comparison/acceleration_chart.py

This PR adds vertical accelerations as well as body frame ones.
Easier logs analysis

Acceleration chart change

---

ekf/kalman_implem.c
ekf/kalman_implem.h
ekf/kalman_update_baro.c

Barometer update reduce to only height, no additional velocity estimation.
Additionally:
- raw accel data used in estimation
- no accelerometer damping

ekf: baro update reduce

---

.github/workflows/ci.yml
algebra/tests/README.md
algebra/tests/test.yml
ekf/logs/tests/test.yml
ekf/logs/tests/tests.c
libs/parser/tests/test.yml
tests/trunner_extension/host_pilot_runner_ext.py
tests/trunner_extension/vpilot_runner_ext.py

Enables running CI tests.
Run tests on every pull request

Activate ci

---

quadcontrol/config.c
quadcontrol/control.c
quadcontrol/control.h
quadcontrol/pid.c

Changes in autonomous modes implementation.
- new takeoff/landing/hover implementation
- changes in motorCtrl

quad-control: autonomous modes changes

---

ekf/kalman_implem.c
ekf/kalman_update_imu.c

ekf: fix new magnetic model

---

scripts/ekf_logs/common/formats/binary/bin_export.py
scripts/ekf_logs/common/formats/binary/bin_parser.py
scripts/ekf_logs/common/formats/binary/structs.py
scripts/ekf_logs/common/formats/csv/csv_export.py
scripts/ekf_logs/common/formats/csv/csv_parser.py
scripts/ekf_logs/common/models/log_data.py

ekf log script: addjust parsing and exporting for new magnetic model

---

ekf/ekflib.c
ekf/kalman_update_gps.c
quadcontrol/control.c

Corrections in landing procedure:
- proper spoolup triggering
- new landing stages:
- new, drop-checking landing mode

quad-control: landing mode correction

---

quadcontrol/config.c
quadcontrol/control.c
quadcontrol/control.h

- adding `flyto` mode that commands the drone in three dimensions
- add simple RTH in `quad_manual`
- fixing heading printing in `cmdCockpit`
- `flyto` mode will be main mode for flying the drone autonomously point-to-point
- simp,le RTH in `quad_manual` allows for simple drone comeback or presentation of position changing capabilities 
- [ x Breaking change (fix or feature that would cause existing functionality to change)

quad-control: `flyto` mode

---

scripts/file_transfer/transfer.py

This PR provides progress bar for file transfer script
- better transfer file time estimates
- knowing that everything is working correctly

File transfer: add progress bar

---

algebra/include/quat.h
algebra/quat.c
ekf/ekflib.c
ekf/ekflib.h
ekf/kalman_implem.h
ekf/meas.c
ekf/meas.h
libs/parser/parser.c
libs/parser/parser.h
quadcontrol/config.c
quadcontrol/control.c
quadcontrol/control.h

- This update adds fully implemented straight-line (point-to-point) navigation based on lat/lon coordinates in `q_mission` file.
- flight modes reduced to only: takeoff/waypoint/landing/manual
- new waypoint mode that flies in a straight line from current position to the target position

quad-control: waypoint navigation update
